server:
  port: 8081 # 占用端口号

spring:
  application:
    name: permission-service # 项目名称
  main:
    allow-circular-references: true # 允许循环依赖
  datasource:
    druid:
      max-evictable-idle-time-millis: 1800000 # 最大空闲时间
      min-evictable-idle-time-millis: 600000 # 最小空闲时间
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/permission?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1w34567890A
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    requested-heartbeat: 60 # 心跳测试间隔
    connection-timeout: 30 # 连接超时时间
    listener:
      simple:
        retry:
          enabled: true # 允许消费重试
          max-attempts: 5 # 最大消费重试次数
          multiplier: 1 # 每次重试间隔乘以1
          initial-interval: 5000 # 初始化消费重试间隔
    host: localhost
    port: 5672
    virtual-host: /itxiaoqi
    username: admin
    password: 1w34567890A

seata:
  enabled: true
  enable-auto-data-source-proxy: false
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: user-permission
  # 修正服务映射配置（添加缩进）
  service:
    vgroup-mapping:
      user-permission: "default"

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 标注xml文件位置
  type-aliases-package: com.itxiaoqi.permissionservice.entity.po # 类型别名包位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出控制台
    map-underscore-to-camel-case: true # 开启驼峰映射

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: info
    com.itxiaoqi: info
#    io.seata: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  config: classpath:log/logback.xml # 日志配置文件
